version: '3'

services:
  auto:
    build: .
    container_name: auto

    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - logs:/log
    ports:
      - "8001:8001"
    networks:
      - linkcar
    environment:
      - MONGO_DB=auto  # Add this line to define the database name
      - MONGO_PORT=27017  # Ensure the port is correctly defined

  mongodb:
    image: mongo
    restart: always
    expose:
      - "27017"
volumes:
  logs:
networks:
  linkcar:
    external: true

