version: '3'

services:
  auto:
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

    volumes:
      - .:/auto
    ports:
      - "8000:8000"
    depends_on:
      - postgres


  postgres:
    image: postgres
    ports:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: otol

volumes:
  db: