version: '3'

services:
  fleet:
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"

    volumes:
      - logs:/log
    ports:
      - "8000:8000"

  mongodb:
    image: mongo
    restart: always
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=poiuytrewq
    volumes:
      - type: bind
        source: ../data
        target: /data/db

volumes:
  mongodb-data:
  logs:

