"""Initial migration

Revision ID: 11e14ef747dc
Revises: 
Create Date: 2024-04-18 09:50:37.007664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e14ef747dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_name', sa.String(), nullable=True),
    sa.Column('connection_status', sa.Boolean(), nullable=True),
    sa.Column('sim_number', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.String(), nullable=True),
    sa.Column('car_model', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('last_active_at', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
